name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set dynamic homepage and CNAME
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "main" ]; then
            echo "www.askhanhassan.com" > public/CNAME
            npm pkg set homepage=https://www.askhanhassan.com
          else
            echo "dev.askhanhassan.com" > public/CNAME
            npm pkg set homepage=https://dev.askhanhassan.com
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
