name: Auto Deploy React to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set CNAME and homepage
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            echo "www.askhanhassan.com" > public/CNAME
            npm pkg set homepage="https://www.askhanhassan.com"
            echo "DEPLOY_BRANCH=gh-pages-prod" >> $GITHUB_ENV
          elif [ "$BRANCH" = "dev" ]; then
            echo "dev.askhanhassan.com" > public/CNAME
            npm pkg set homepage="https://dev.askhanhassan.com"
            echo "DEPLOY_BRANCH=gh-pages-dev" >> $GITHUB_ENV
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: ${{ env.DEPLOY_BRANCH }}
